import type { SessionListItem } from '../../types/session';

/** Realistic mock sessions for variant comparison */
export const MOCK_SESSIONS: SessionListItem[] = [
  {
    id: 1,
    durationSeconds: 210,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    errorCount: 3,
    improvementCount: 5,
    polishCount: 2,
    title: 'Morning check-in about project deadlines',
    description: 'Discussed quarterly review process with team',
    topicCategory: 'work',
    clarityScore: 82,
    totalFillerCount: 7,
    agentId: 1,
    agentName: 'Dr. Aris',
    agentAvatarSeed: 'dr-aris-seed',
  },
  {
    id: 2,
    durationSeconds: 145,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    errorCount: 1,
    improvementCount: 3,
    polishCount: 6,
    title: 'Ordering coffee and making small talk',
    description: 'Practice casual conversation',
    topicCategory: 'daily_life',
    clarityScore: 91,
    totalFillerCount: 2,
    agentId: 2,
    agentName: 'Sophia',
    agentAvatarSeed: 'sophia-travel',
  },
  {
    id: 3,
    durationSeconds: 380,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    errorCount: 8,
    improvementCount: 4,
    polishCount: 1,
    title: 'Explaining technical architecture',
    topicCategory: 'technology',
    clarityScore: 64,
    totalFillerCount: 14,
    agentId: null,
    agentName: 'Reflexa',
    agentAvatarSeed: null,
  },
];
